from .StudentManagement import delete_student,update_student,search_student,add_student,view_students
from .AttendanceManagement import mark_attendance,view_attendance
from .MarksManagement import add_marks,view_report_card
